In [1]:
import numpy as np

In [2]:
x = [2, 4, 5, 3, 6]
y = np.array(x)

In [3]:
print(y)
print(type(y))

[2 4 5 3 6]
<class 'numpy.ndarray'>


In [15]:
aa = []
for i in range(1, 5):
    ai = int(input('Enter a number:'))
    aa.append(ai)
print(np.array(aa))

Enter a number: 625
Enter a number: 6
Enter a number: 62
Enter a number: 5


[625   6  62   5]


In [16]:
print(y.ndim)#To check dimension of the array

1


In [25]:
arrey2d = np.array([[1,23,3,4,5], [3,4,3,2,33], [1,23,3,4,5], [3,4,3,2,33]])
print(arrey2d)

yex = np.array('This is a 3D array below')
print(yex)

arrey3d = np.array([[[1,23,3,4,5], [3,4,3,2,33], [1,23,3,4,5], [3,4,3,2,33]]])
print(arrey3d)

[[ 1 23  3  4  5]
 [ 3  4  3  2 33]
 [ 1 23  3  4  5]
 [ 3  4  3  2 33]]
This is a 3D array below
[[[ 1 23  3  4  5]
  [ 3  4  3  2 33]
  [ 1 23  3  4  5]
  [ 3  4  3  2 33]]]


In [27]:
yux = np.array([1, 3, 4, 5], ndmin = 6) #shortcut to make multidimensional array
print(yux)

[[[[[[1 3 4 5]]]]]]


In [2]:
a0 = np.zeros((4,5))
print(a0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
ar = np.arange(8)
print(ar)

[0 1 2 3 4 5 6 7]


In [8]:
ad = np.eye(5)
print(ad)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
ad.shape

(5, 5)

In [11]:
x = [2, 4, 5, 3, 6]
y = np.array(x)

In [12]:
print(y)

[2 4 5 3 6]


In [17]:
z = [10, 20, 30]
yo = np.array(z)
print(yo)
ya = yo + 3
print(ya)
ye = yo * 2
print(ye)

[10 20 30]
[13 23 33]
[20 40 60]


In [18]:
[10,20,30] * 2

[10, 20, 30, 10, 20, 30]

In [19]:
np.mean(z)

np.float64(20.0)

In [3]:
%pip install ipympl

   ---------------------------------------- 0.0/519.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/519.0 kB ? eta -:--:--
    --------------------------------------- 10.2/519.0 kB ? eta -:--:--
   --- ----------------------------------- 41.0/519.0 kB 495.5 kB/s eta 0:00:01
   --------------------- ------------------ 276.5/519.0 kB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 519.0/519.0 kB 4.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
%matplotlib widget